config/routes.rb
FirstDeveloper::Application.routes.draw do
  root :to => "entries#index"
  resources :entries

end

app/models/category.rb
class Category < ActiveRecord::Base

	# ATTRIBUTES
	attr_accessible :name

	# ASSOCIATIONS
	has_and_belongs_to_many	:entries

	# VALIDATIONS
	validates :name, :presence => true

	# TODO: Avoid nil name values


	# METHODS

	def self.ids_from_tokens( tokens )
		# tokens is like 'cat1, ‚ ...etc'
		real_tokens = tokens.split(",")

		ids = {}   # Containing the newest category ids

		# Looking for all ready exist tokens
		real_tokens.each do |name| 
			category = Category.where(name: name)

			puts category.nil?
			id = 
			if category.empty?
				ids[name] = Category.create!(name: name).id
			else
				ids[name] = category.first.id
			end
		end

		ids.values
	end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  # HELPERS
  acts_as_commentable
  extend FriendlyId
  friendly_id :title, :use => :slugged


	# CONSTANTS
  LIMIT_WORD_COUNT = 250

	# ATTRIBUTES
	attr_accessible  :title, :body, :category_tokens, :category_ids, :type_id
	attr_reader :category_tokens

	# ASSOCIATIONS
	has_and_belongs_to_many 	:categories
  belongs_to 					      :type

	# VALIDATIONS
	validates :title, :body, :presence => true

	# METHODS

	def category_tokens=(tokens)
		self.category_ids = Category.ids_from_tokens(tokens)
	end

	# Returns a string with elements separated by comma
	def categories_stringlified
		result = ""
		cats = categories;
		unless ( cats.blank? ) 
			arr_result = cats.collect do |c|
				c.name
			end
			result = arr_result.join(",")
		end
		return result
	end 

  def has_excerpt?
    self.body.size > LIMIT_WORD_COUNT
  end
	
  # To check whether an entry has its type included in Type::TYPES
	# Type::TYPES.each do |type| 
	# 	define_method "#{type}?" do
	# 		type.exists?(:name => role_type) 
	# 	end
	# end

end

app/models/type.rb
class Type < ActiveRecord::Base

  # ATTRIBUTES
  attr_accessible :name
  # ASSOCIATIONS
  has_many  :entries

  # VALIDATIONS

  # METHODS
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # METHODS

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
    # Prepopulate categories
    @categories = @entry.categories_stringlified;
    
  end

  # POST /entries
  # POST /entries.json
  def create

    
    @entry = Entry.new(params[:entry])

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry has been well created" }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        flash[:errors] = "Entry hasn't been created! Verify that every required fields are filled." 
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    
    @entry = Entry.find(params[:id])

    tokens = params[:entry][:category_tokens].to_s
    
    params[:entry][:category_ids] = Category.ids_from_tokens(tokens)
    
    tokens = params[:entry].delete([:category_tokens])
    
    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was nicely updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit", notice: 'Something goes wrong when you updated this entry' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time_info time
		time.to_s(:long)
	end

	# 
	def link_to_add_entry
		icon_text = '<i class="icon-plus"></i>'.html_safe
		url = new_entry_path
		classes = 'btn'
		link_to icon_text, url, id: "add_entry_btn", class: classes 
	end

	# Format body text using Markdown
	def markdown(text) 
		options 	= [filter_html: false, no_intra_emphasis: true]
		renderer 	= Redcarpet::Render::HTML.new(*options)
	    extensions 	= {fenced_code: true, autolink: true}
	    markdown 	= Redcarpet::Markdown.new(renderer, extensions)
		markdown.render(text).to_html.html_safe
	end


  # generate id attribute for record 
  def attr_id_for record 
    [record.class.name.downcase, record.id].to_s.parameterize
  end
end

app/helpers/entries_helper.rb
module EntriesHelper

	def formated_body (body)
		RedCloth.new(body).to_html
	end

end

app/views/entries/_entry.html.erb
<% available ||= false %>

<div>
	<% with_actions_btns ||= false %>
	
	<% unless entry.blank? %>
  <% entry_type = entry.type.blank? ? "" : entry.type.name %> 	
	<article id="<%= attr_id_for(entry) %>" class="fd-ui-tl-item">
		<span class="fd-ui-icon <%= entry_type %>"></span>
		<span class="fd-ui-tl-item-indic"></span>
		<header class="fd-ui-tl-item-hd">
			<span class="fd-ui-avt small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>

			<!-- Like buttons -->
			<% if available %>
			<div class="fd-ui-like-btns">
				<span class="fd-ui-like-btn up">+8</span>
				<span class="fd-ui-like-btn down">-12</span>
			</div>
			<% end %>

			<div id="" class="fd-ui-actions btns">
				<i class="fd-ui-icons icon-clip fd-ui-btn"></i>
        <a href="#"  class="tweet" data-url="http://jsfiddle.net" data-via="JoelBesada" data-text="Some text to describe the link" 
              data-related="js_fiddle"  data-hashtags="tag">
          <span class="count">0</span>
        </a>

			</div>
		</header>
		
	<div id=""  class="fd-ui-tl-item-ct">
		<div id=""  class="fd-ui-tl-item-ct-el full-size">
			<hgroup class="fd-ui-tl-item-title">
				<h4>By <span class="author">Nathan Pitman</span> | <%= time_info entry.created_at %></h4>
				<h1>
          <% if action_name == "edit" || action_name == "show" %>
            <%= entry.title %>
          <% else %>
            <%= link_to entry.title, entry_path(entry) %>
          <% end %>
        </h1>
				<p class="details">
				
				<% unless entry.categories.blank? %>
					<% entry.categories.each do |category| %>
					<span class="fd-ui-cst-btn category f-l"><%= category.name.to_s.capitalize %></span>
					<% end %>
				<% end %>

					<span class="fd-ui-cst-btn tag-style f-r">26 Comments →</span><span class="clear"></span>
				</p>
			</hgroup>
			<div class="fd-ui-item-ct-text">
				<%= markdown(entry.body) unless entry.body.nil? %>
        <% if entry.has_excerpt? %>
        <button class="btn continue-reading">Continue reading</button>
        <% end %>
			</div>
		</div>

		<%#= render "shared/entry_extras_slot" %>
		
		<%= render "shared/comments_slot" %>

		<%= render "shared/show_more_slot" %>


		<%# ----------   Action buttons ------------  %>
		<% if with_actions_btns %>
		<div id=""  class="fd-ui-tl-item-ct-el full-bg">
			<%= link_to 'Edit', edit_entry_path(entry), :class => 'btn' %>
			<%= link_to 'Delete', 
			          entry_path(entry), 
			          :method => 'delete', 
			          :confirm => 'Are you sure?', 
			          :class => 'btn danger' %>
	      	<%= link_to 'Back', entries_path, :class => 'btn primary'  %>
	    </div>  
	    <% end %>
	</div>
	<footer class="fd-ui-tl-item-ft"></footer>
</article>
<% end %> 

app/views/entries/_form.html.erb
<% tokens ||= "" %>

<%= simple_form_for @entry, :html => { :class => 'form-horizontal' } do |f| %>
<article id="" class="fd-ui-tl-item fd-ui-slot-container">
	<span class="fd-ui-icon post"></span>
	<span class="fd-ui-tl-item-indic"></span>
	<header class="fd-ui-tl-item-hd">
		<span class="fd-ui-avt small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
		<div id="" class="fd-ui-actions btns">
			<i rel="tooltip" title="more" class="fd-ui-icons icon-more fd-ui-btn"></i>
		</div>
	</header>
	<div id=""  class="fd-ui-tl-item-ct">
		<div id=""  class="fd-ui-tl-item-ct-el full-size">
			<hgroup class="fd-ui-tl-item-title">
				<h4>By <span class="author">Nathan Pitman</span> | <%= time_info(Time.now) %></h4>
				<h1>
					<%= f.text_field :title, class: "text_field title-for-content-slot",
							placeholder: "Enter title here …" %>
				</h1>

			</hgroup>
			<div class="fd-ui-item-ct-text">
				<%= f.text_area :body, class: 'text_area body-for-content-slot', placeholder: "What's up dude ? " %>
			</div>
		</div>

		<%#= render "shared/entry_extras_slot" %>

		<%#= render "shared/comments_slot" %>

		<div id=""  class="fd-ui-tl-item-ct-el full-bg">
			<i class="icon-tasks slot-label"></i>
			<%= f.text_field :category_tokens, class: "entry-category-slot", value: "#{tokens}" %>
		</div>	

		<%= render "shared/type_choice_slot", f: f %> 

		<div id=""  class="fd-ui-tl-item-ct-el full-bg">
			<p class="fd-ui-checkbox"><input type="checkbox" class="checkbox-slot" />Publish this post.</p>
		</div>

		<div id=""  class="fd-ui-tl-item-ct-el full-bg">
			<%= f.submit "Save", :class => 'btn default' %>
			<%= link_to 'Cancel', entries_path, :class => 'btn primary' %>
		</div>  

	</div>
	<footer class="fd-ui-tl-item-ft"></footer>
</article>
<% end %>

app/views/entries/edit.html.erb
 
<%= render :partial => 'form', locals: {tokens: @categories}   %>

app/views/entries/index.html.erb
<% unless @entries.blank? %>
	<%  @entries.each do |entry| %>
		<%= render "entry", entry: entry, with_actions_btns: true %>
	<% end %>
<% end %>

app/views/entries/new.html.erb
<%= render :partial => 'form' %>

app/views/entries/show.html.erb
<%= render "entry", entry: @entry %>

app/views/layouts/_action_box_form.html.erb
<% buttons ||= nil %>

<div id=""  class="fd-ui-tl-item-ct-el full-bg">
	<% buttons.each do | name, link, class | %>
		<a class="btn default" href="<%= link %>"><%= name %></a>
	<% end %>	
</div>	

app/views/layouts/_ct-header.html.erb
<header id="header" class="fd-ui-ct-header">
	
	<a id="hire-me" class=""></a>
	
</header>


	

app/views/layouts/_footer.html.erb
<%= javascript_include_tag "application" %>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstDeveloper</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

<%# -------  Navigation bar ---------- %>
<%= render "layouts/navbar" %>


<%# ------- Header page content  -------- %>
<%#= render "layouts/ct-header" %>

app/views/layouts/_navbar.html.erb
<% available ||= false %>

<div class="navbar navbar-fixed-top">

	<!--	NOTIFICATION AREA   -->
	
	<% flash.each do |key, msg| %>	
		<% unless flash[key].blank?  %>
		<div id="notification_area" class="fd-ui-flash-msg <%= key %>">
			<i class="flash-icon">
				<img src="<%= asset_path("ui/loader.gif"); %>" alt="">
			</i>
			<p><%= msg %> </p>
			<i class="flash-close">×</i>
		</div>
		<% end %>
	<% end %>

	<!-- 		NATIFICATION BAR  -->
	 
	<div class="navbar-inner">
		<div class="container-fluid">

			<!--   LOGO   -->
      <a id="logo" class="logo" href="/"></a>

			<!--    SEARCH BAR    -->
			<% if available %>
			<div class="fd-hd-search-form">
				<form action="_ct-header_submit" method="get" accept-charset="utf-8">
					<input type="search" name="" value="" placeholder="What are you looking for?">		
				</form>
			</div>
			<% end %>

			<!--     NAVIGATION BAR COLLAPSE    -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>

			<!--      MENU     -->
			<div class="nav-collapse">
				<!-- .nav, .navbar-search, .navbar-form, etc -->
				<ul class="nav pull-right">
					<li class="">
						<a href="#" id="hire-me">Hire me</a>
					</li>
					<li class="">
						<a href="#">+ Labs</a>
					</li>
					<li class="">
						<a href="#">Illustrations</a>
					</li>
					<li class="">
						<a href="#">About me</a>
					</li> 
					<li class="">
						<a href="#">Contact me</a>
					</li>
					<li class="divider-vertical no mr"></li>
					<li class="dropdown">
						<a data-toggle="dropdown" class="dropdown-toggle" href="#"></i> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="#">Features</a></li>
							<li><a href="#">Support</a></li>
							<li><a href="#">Feedback</a></li>
							<li class="divider"></li>
							<li><a href="#">Help</a></li>
						</ul>
					</li>
				</ul>
			</div>
		
		</div>
	</div>
</div>

app/views/layouts/_sidebar.html.erb
<% all_categories ||= Category.all %>

<span href="" class="hide-sidebar opened"></span>
<aside id="sidebar">
	<ul class="sidebar-menu">
		<li class="">
			<a href="#">BLOG</a>
			<ul class="sidebar-submenu">
				<% unless all_categories.blank? %>
				<% all_categories.each do |category| %>
				<%  unless (count = category.entries.size).zero? %>
				<li title="<%= category.name %>">
					<a class="">
						<span class="count"><%= count %></span>
						<%= category.name %>
					</a>
				</li>
				<% end %>
				<% end %>
				<% end %>
			</ul>
		</li>
	</ul>
</aside>

<%# <i class="icon-plus icon-white pull-right"></i> %>

app/views/layouts/_sidebar_infos.html.erb
<span href="" class="hide-sidebar-info closed" ></span>

<aside id="sidebar_infos" >

	<%#------------		Me and my profile  -----------------%>
	<section class="me profile ">
		<span id="" class="avatar big" style="background-image:url(<%= asset_path("ui/me.jpg"); %>)"></span>
		<div class="info">
			<dl>
				<dt><span class="fst-txt">Lionel</span> LONKAP TSAMBA</dt>
				<dd>Freelance developer</dd>
			</dl>
			<p><span class="fst-txt">Villeneuve d'ascq | </span><span class="snd-txt">FRANCE</span></p>
		</div>
	</section>

	<%#-----------------  What about me?  -----------------%>
	<section class="me about">
		<h3 class="section-title">About me?</h3>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
		</p>
	</section>

	<%#-----------------	Social networks  -----------------%>
	<section class="me ntkw">
		<h3 class="section-title">Am i social?</h3>
		<ul id="" class="">
			<li><a href="" title="skype" class="fd-social skype"></a></li>
			<li><a href="" title="skype" class="fd-social facebook"></a></li>
			<li><a href="" title="skype" class="fd-social google-plus"></a></li>	
			<li><a href="" title="skype" class="fd-social twitter"></a></li>
			<li><a href="" title="skype" class="fd-social github"></a></li>
		</ul><!-- / -->
	</section>
	<span class="clear"></span>

	<%#-----------------  My skills     ---------------------%>
	<section class="me skills">
		<h3 class="section-title">Skills?</h3>
		<ul class="section-tags">
			<li><span class="meta">50%	</span> Programming</li>
			<li><span class="meta">50%	</span> Coding</li>
			<li><span class="meta">50%  </span> Webdesign/Photoshop</li>
			<li><span class="meta">50%</span> Sport</li>
			<li><span class="meta">50%	</span> Inspiration</li>
		</ul>			
	</section>
	
</aside>

app/views/layouts/_timeline_slots_box.erb
<% ["post", "video","music", "edit", "update"].each do |type|%>
<article id="" class="fd-ui-tl-item">
	<span class="fd-ui-icon <%= type %>"></span>
	<span class="fd-ui-tl-item-indic"></span>
	<header class="fd-ui-tl-item-hd">
		<span class="fd-ui-avt small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
		<div id="" class="fd-ui-actions btns">
			<% ["share", "heart","star", "clip", "more"].each do |name| %>
			<i rel="tooltip" title="<%= name %>" class="fd-ui-icons icon-<%= name %> fd-ui-btn"></i>
			<% end %>
		</div>
	</header>
	<div id=""  class="fd-ui-tl-item-ct">
		<div id=""  class="fd-ui-tl-item-ct-el full-size">
			<hgroup class="fd-ui-tl-item-title">
				<h4>By <span class="author">Nathan Pitman</span> | November 17, 2010</h4>
				<h1>Working on the UI for a web app we're developing</h1>
				<p class="details"> 
					<span class="fd-ui-cst-btn tag f-l">Ruby</span>
					<span class="fd-ui-cst-btn tag f-l">Programming</span>
					<span class="fd-ui-cst-btn tag-style f-r">26 Comments →</span><span class="clear"></span></p>
				</hgroup>
				<div class="fd-ui-item-ct-text">
					<%= render("shared/audio_player") %>
					<!--<iframe width="604" height="375" frameborder="0" allowfullscreen="" src="http://blip.tv/play/AYLv%2BzQC.html?p=1" style="border: 1px none; margin: 21px;"></iframe>-->

					<% text = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut ore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

					h3. Organize your template files →

					h4. Everything about templating sytem


					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \"first-developer.fr\":http://first-developer.fr Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.

						p(fd\-ui\-text\-info). <i class=\"icon-share-alt\"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit, seo eiusmod tempor incididu " 
						%>
						<%= raw RedCloth.new(text).to_html %>

						<button class="btn continue-reading">Continue reading</button>

					</div>
				</div>	
				<div id=""  class="fd-ui-tl-item-ct-el full-bg">
					<div class="liking">
						<div class="f-r likes">
							<i class="fd-ui-icons icon-heart fd-ui-btn like"></i><span class="likes-count">125</span>
						</div>
						<div class="likers f-r">
							<span class="fd-utils-avatar small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
							<span class="fd-utils-avatar small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
							<span class="fd-utils-avatar small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
						</div>

					</div>
				</div>
				<div id=""  class="fd-ui-tl-item-ct-el full-bg">
					<input type="text"  class="full" name="" value="" placeholder="Enter your comment here ...">
				</div>	
				<div id=""  class="fd-ui-tl-item-ct-el full-bg">
					<div id="" class="fd-ui-flash-msg warning">
						<i class="flash-icon"><img src="<%= asset_path("ui/loader.gif"); %>" alt=""></i><p>You must login to comment this post!</p>
						<i class="flash-close">×</i>
					</div>
				</div>	
				<div id=""  class="fd-ui-tl-item-ct-el full-bg">
					<button class="btn default">Save   </button>
					<button class="btn primary">Cancel </button>
					<button class="btn  danger">Delete </button>
				</div>	
				<div id=""  class="fd-ui-tl-item-ct-el full-bg">
					<ol id="" class="fd-ui-comments">
						<% 3.times do %>
						<li class="cmt">
							<div class="cmt-avt">
								<span class="fd-utils-avatar small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
							</div>
							<div class="cmt-ct">
<!-- <div class="cmt-ct-hd">
<a href="" class="cmt-user">Chris Brown</a>
</div> -->
<div class="cmt-ct-txt">
	<p> <a href="" class="cmt-user">Chris Brown <span class="arrow">→</span> </a>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua.
	</p>
</div>
<div class="cmt-ct-ft">
	<span class="cmt-time">Il y a 25 minutes | 21h15</span>
</div>
</div>
<span class="clear"></span>

<ol class="cmt-reply">
	<% 3.times do %>
	<li>
		<div class="cmt-avt">
			<span class="fd-utils-avatar small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
		</div>
		<div class="cmt-ct">
			<div class="cmt-ct-txt">
				<p> <a href="" class="cmt-user">Chris Brown <span class="arrow">→</span> </a>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua.
				</p>
			</div>
			<div class="cmt-ct-ft">
				<span class="cmt-time">Il y a 25 minutes | 21h15</span>
			</div>
		</div>
	</li>
	<% end %>
</ol>
</li>
<% end %>
</ol><!-- / -->
</div>	
<div id=""  class="fd-ui-tl-item-ct-el full-bg">
	<button class="btn more"><i class="icon-chevron-down"></i></button>
</div>	
</div>
<footer class="fd-ui-tl-item-ft">

</footer>
</article>
<% end %>

app/views/layouts/_toolbar.html.erb
<div id="" class="fd-ui-tools">
	<div class="btn-group" data-toggle="buttons-radio">
		<%= link_to_add_entry %>
		<button class="btn"><i class="icon-eye-open"></i></button>
		<button class="btn"><i class="icon-qrcode"></i></button>
		<button class="btn"><i class="icon-cog"></i></button>
	</div>
  <%= render "shared/siri.html.erb" %>
</div>

app/views/layouts/application.html.erb
<!-- HEADER -->
<%= render "layouts/header" %>
  
<%#= render "shared/modal" %>

<!-- ==========  MAIN CONTAINER  ========== -->

<div  class="fd-ui-container">

	<!-- Sidebar navigation -->
	<div id="fd-ui-sidebar-left">
		<%= render "layouts/sidebar" %>
	</div>
	<div id="fd-ui-center" >
		<!-- Toolbar -->
		<%= render "layouts/toolbar" %>

		<!-- Timeline -->
		<div class="timeline">
			<%= yield %>
		</div>
	</div>
	<!-- Sidebar my profile -->
	<div id="fd-ui-sidebar-right2" class="sidebar-closed">
		<%= render "layouts/sidebar_infos" %>
	</div>
	
</div>


<!-- FOOTER -->
<%= render "layouts/footer" %>

app/views/shared/_action_btns_slot.html.erb
<div id=""  class="fd-ui-tl-item-ct-el full-bg">
	<button class="btn default">Save   </button>
	<button class="btn primary">Cancel </button>
	<button class="btn  danger">Delete </button>
</div>	

app/views/shared/_multi_form.html.erb
<%= form_for entry, :html => { :class => 'form-horizontal' } do |f| %>
<article id="" class="fd-ui-tl-item fd-ui-slot-container">
	<span class="fd-ui-icon post"></span>
	<span class="fd-ui-tl-item-indic"></span>
	<header class="fd-ui-tl-item-hd">
		<span class="fd-ui-avt small default" style="background-image:url(<%= asset_path("ui/fd-ui-ux-sprite.png"); %>)"></span>
		<div id="" class="fd-ui-actions btns">
			<i rel="tooltip" title="more" class="fd-ui-icons icon-more fd-ui-btn"></i>
		</div>
	</header>
	<div id=""  class="fd-ui-tl-item-ct">
		<div id=""  class="fd-ui-tl-item-ct-el full-size">
			<hgroup class="fd-ui-tl-item-title">
				<h4>By <span class="author">Nathan Pitman</span> | <%= time_info(Time.now) %></h4>
				<h1>
					<%= f.text_field :title, 
							class: "text_field title-for-content-slot", 
							placeholder: "Enter title here …" %>
				</h1>
				
			</hgroup>
			<div class="fd-ui-item-ct-text">
				<%= f.text_area :body, 
						class: 'text_area body-for-content-slot',
						placeholder: "What's up dude ? " %>
			</div>
		</div>

		<%#= render "shared/entry_extras_slot" %>
		
		<%#= render "shared/comments_slot" %>
		
		<%= render "shared/category_slot" %>

		<div id=""  class="fd-ui-tl-item-ct-el full-bg">
			<i class="icon-tags slot-label"></i>
			<input type="text" class="entry-tags-slot" value="" />
		</div>	

		<div id=""  class="fd-ui-tl-item-ct-el full-bg">
			<p class="fd-ui-checkbox"><input type="checkbox" class="checkbox-slot" />Publish this post.</p>
		</div>

		<%= render "shared/action_btns_slot" %>

	</div>
	<footer class="fd-ui-tl-item-ft"></footer>
</article>


  <fieldset>
    <legend><%= controller.action_name.capitalize %> Entry</legend>

    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :body, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :body, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :published, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :published, :class => 'check_box' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "create entry", :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', entries_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>